name: Build and test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: 1
      OS: linux
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc-mipsel-linux-gnu cmake ninja-build libsdl2-dev
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Generate PSY-Q 4.7 SDK
        run: make -j
      - name: Check if PSY-Q 4.0 decomp matches
        working-directory: decomp/
        run: |
          make dependencies
          (make clean && make all) || cat psyq400.map
      - name: Compile sample (PC)
        working-directory: samples/gpu_hello
        run: cmake -GNinja -DSDL_STATIC=ON -B build/  && cmake --build build/
      - name: Test PsyZ
        working-directory: psyz/
        run: make test
      - name: Upload test failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-linux
          path: psyz/tests/expected/*.actual.png
          if-no-files-found: ignore

  build-and-test-windows:
    runs-on: windows-latest
    env:
      CI: 1
      OS: windows
    strategy:
      matrix:
        compiler:
          - name: MSVC
            script: test.bat
          - name: ClangCl
            script: test-clang.bat
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test PsyZ on Windows (${{ matrix.compiler.name }})
        working-directory: psyz/
        run: ./${{ matrix.compiler.script }}
        env:
          GTEST_FILTER: "-gpu_Test.*"
      - name: Upload test failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-windows-${{ matrix.compiler.name }}
          path: psyz/tests/expected/*.actual.png
          if-no-files-found: ignore

  build-and-test-macos:
    runs-on: macos-latest
    env:
      CI: 1
      OS: darwin
    steps:
      - name: Install requirements
        run: brew install cmake ninja sdl2
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test PsyZ
        working-directory: psyz/
        run: make test
      - name: Upload test failure artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures-macos
          path: psyz/tests/expected/*.actual.png
          if-no-files-found: ignore
